<!doctype html>
<html lang="id"><head><meta charset="UTF-8"><style>
*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#263238;font-size:10px}.header{text-align:center;border-bottom:3px solid #344767;padding-bottom:12px;margin-bottom:16px}.header h1{font-size:18px;margin:0 0 4px;color:#344767}.header p{margin:0;color:#67748e}.meta{width:100%;border-collapse:collapse;background:#f4f6f8;margin-bottom:16px}.meta td{padding:6px 8px}.label{font-weight:bold;color:#344767;width:120px}.summary{width:100%;border-collapse:separate;border-spacing:6px;margin-bottom:14px}.summary td{border:1px solid #e1e5ea;text-align:center;padding:8px;width:25%}.number{font-size:16px;font-weight:bold;color:#344767}.caption{font-size:8px;color:#67748e}.data{width:100%;border-collapse:collapse}.data th{background:#344767;color:#fff;text-align:left;padding:7px 6px;font-size:8px}.data td{padding:7px 6px;border-bottom:1px solid #e5e7eb}.center{text-align:center}.badge{font-weight:bold}.footer{margin-top:18px;border-top:1px solid #ddd;padding-top:8px;text-align:center;color:#8392ab;font-size:8px}
</style></head><body>
<div class="header"><h1>Laporan Hasil Quiz</h1><p>Equip Discipleship Learning Management System</p></div>
<table class="meta"><tr><td class="label">Kelas</td><td>{{ $selectedKelas->nama_kelas }}</td><td class="label">Sesi</td><td>Sesi {{ $selectedSesi->urutan }} - {{ $selectedSesi->judul }}</td></tr><tr><td class="label">Batch</td><td>{{ $selectedBatch->nama_batch }}</td><td class="label">Quiz</td><td>{{ $quiz->judul }}</td></tr></table>
<table class="summary"><tr><td><div class="number">{{ $summary['participants'] }}</div><div class="caption">PESERTA</div></td><td><div class="number">{{ $summary['submitted'] }}</div><div class="caption">MENGUMPULKAN</div></td><td><div class="number">{{ $summary['average'] }} / {{ $summary['max_score'] }}</div><div class="caption">RATA-RATA NILAI</div></td><td><div class="number">{{ $summary['passed'] }}</div><div class="caption">LULUS</div></td></tr></table>
<table class="data"><thead><tr><th>No</th><th>Peserta</th><th>Email</th><th>Status</th><th class="center">Nilai</th><th class="center">Persentase</th><th>Pengumpulan</th></tr></thead><tbody>@foreach($reports as $index => $report)<tr><td>{{ $index + 1 }}</td><td>{{ $report['user']->nama_lengkap ?? $report['user']->name }}</td><td>{{ $report['user']->email }}</td><td>@if(!$report['attempt'])Belum mengerjakan@elseif($report['attempt']->status === 'needs_review')Perlu review esai@elseif($report['passed'])Lulus@elseBelum lulus@endif</td><td class="center">{{ $report['score'] !== null ? $report['score'] . ' / ' . $summary['max_score'] : '-' }}</td><td class="center">{{ $report['attempt'] ? $report['percentage'] . '%' : '-' }}</td><td>{{ $report['attempt']?->submitted_at?->format('d M Y H:i') ?? '-' }}</td></tr>@endforeach</tbody></table>
<div class="footer">Dicetak pada {{ now()->format('d F Y H:i') }}</div>
</body></html>
